app:
    resource: "@AppBundle/Controller/"
    type: annotation
    prefix: /Scrum

homepage:
    path: /
    defaults: { _controller: AppBundle:Route:homepage }
    
backlog:
    path: /{owner}/{project}/backlog
    defaults: { _controller: AppBundle:Route:backlog }   
