language: php
php:
    - 5.5

before_script:
    - composer install --no-interaction --working-dir ScrumEnv
    - "wget http://selenium.googlecode.com/files/selenium-server-standalone-2.47.1.jar"
    - "java -jar selenium-server-standalone-2.47.1.jar -role hub > /dev/null &"
    - "java -jar selenium-server-standalone-2.47.1.jar -role node  -hub http://localhost:4444/grid/register > /dev/null &"
    - sleep 5

script:
    - phpunit -c ScrumEnv/app/ -v
