language: php
php:
    - 5.5

before_script:
    - composer install
    - wget http://selenium.googlecode.com/files/selenium-server-standalone-2.33.0.jar
    - "nohup java -jar selenium-server-standalone-2.33.0.jar > /dev/null &"
    - sleep 5

script:
    - phpunit -c app/
