language: php
php:
    - 5.5
    - 5.4
    - hhvm

before_script:
    - "nohup java -jar selenium-server-standalone-2.44.0.jar > /dev/null &"
    - sleep 5

script:
    - phpunit --bootstrap ScrumEnv/vendor/autoload.php

