language: php
php:
    - 5.5
env:
  - SYMFONY_VERSION="2.7.*" DB=mysql
  
before_script:
      - composer install --no-interaction --working-dir ScrumEnv
     - "export DISPLAY=:99.0"
     - "sh -e /etc/init.d/xvfb start"
     - php ScrumEnv/app/console doctrine:database:create --env=test
     - php ScrumEnv/app/console doctrine:schema:update --force --env=test
     - php ScrumEnv/app/console doctrine:fixtures:load --no-interaction --env=test
     - sleep 15
     - "php ScrumEnv/app/console server:run &"

script:
    - phpunit -c ScrumEnv/app/ -v
