#TODO: homepage that list projects for each user  

go_to_backlog:
  pattern: /Backlog/{owner}/{project}/
  defaults: { _controller: ProjectBundle:Default:list }   

go_to_User_Story:
  pattern: /Backlog/{owner}/{project}/Add_UserStory/
  defaults: { _controller: ProjectBundle:Default:Add_Us }   

Delete_User_Story:
  pattern: /Backlog/{owner}/{project}/delete_UserStory/{id}
  defaults: { _controller: ProjectBundle:Default:Delete_Us }   

Update_User_Story:
  pattern: /Backlog/{owner}/{project}/update_UserStory/{id}
  defaults: { _controller: ProjectBundle:Default:Update_Us }   
  
Project:
    pattern: /Project/{owner}/{project}
    defaults: { _controller: ProjectBundle:Default:ProjectOverview }
    
Sprint_creation:
    pattern: /Sprint/new/{owner}/{project}
    defaults: { _controller: ProjectBundle:Sprint:SprintCreation }
